ims/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase/', include('purchase.urls')),
    path('seller/', include('seller.urls')),
    path('customer/', include('customer.urls')),
    path('sale/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('add-product/', views.add_product, name="add-product"),
    path('edit-product/<product_id>/', views.edit_product, name="edit-product"),
    path('del-product/<product_id>/', views.delete_product, name="del-product"),
    path('get-product/<product_id>/', views.get_product, name='get-product'),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

inventory/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=20)
    pic = models.ImageField(default='defaultProduct.png', upload_to='product_pics')
    hsn_code = models.IntegerField()
    qty = models.IntegerField()
    min_stock_alarm = models.IntegerField(default=20)
    measuring_unit_1 = models.CharField(max_length=20)   # Measuring Unit-Smallest
    measuring_unit_2 = models.CharField(max_length=20, blank=True, null=True)   # Measuring Unit
    measuring_unit_relation = models.IntegerField(null=True, blank=True)
    price = models.FloatField()
    gst = models.IntegerField()
     
    def __str__(self):
        return self.name

inventory/views.py
from django.shortcuts import render, redirect, HttpResponse
import json
from .models import Product
from django.core.paginator import Paginator
from django.db.models import Q, ProtectedError
from django.db.models.functions import Lower
from django.contrib import messages

# Create your views here.
def inventory(request):
    # For searching the products
    search_product = request.GET.get('search_product')
    if search_product:
        product = Product.objects.filter(Q(name__icontains=search_product) | Q(hsn_code__icontains=search_product))
    else:
        # If not searched, return default posts
        product = Product.objects.all().order_by(Lower("name"))
    
    p = Paginator(product, 12)  # creating a paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    # context = {'page_obj': page_obj}
    return render(request, 'inventory/inventory.html', {'sb':2, 'page_obj': page_obj})


def add_product(request):
    if request.method == 'POST':
        # print("\n\n##################", request.POST, request.FILES['img'])
        instance = Product()
        instance.name = request.POST['name']
        if bool(request.FILES.get('img', False)) == True:
            instance.pic = request.FILES['img']
        instance.hsn_code = request.POST['hsn']
        instance.qty = request.POST['actual_qty']
        instance.min_stock_alarm = request.POST['min_stock_alarm']
        instance.measuring_unit_1 = request.POST['mu_1']
        if (request.POST['mu_2'] != ''): 
            instance.measuring_unit_2 = request.POST['mu_2']
        if (request.POST['mr'] != ''): 
            instance.measuring_unit_relation = request.POST['mr']
        instance.price = request.POST['price']
        instance.gst = request.POST['gst']
        try:
            instance.save()
            messages.success(request, "Product added successfully.")
            return redirect('inventory:inventory')
        except:
            messages.error(request, "Error, product not added!")
    return render(request, 'inventory/addProduct.html', {'sb':2})

def delete_product(request, product_id):
    try:
        product_instance = Product.objects.get(pk=product_id)
    except:
        messages.error(request, "Product not found!")
        return redirect('inventory:inventory')
    
    try:
        product_instance.delete()
        messages.success(request, "Product successfully deleted.")
    except ProtectedError:
        messages.error(request, "Product can't be deleted!!")
    except:
        messages.error(request, "Error while deleting the product!")
    finally:
        return redirect('inventory:inventory')

def edit_product(request, product_id):
    try:
        product_instance = Product.objects.get(pk=product_id)
    except:
        messages.error(request, "Product not found!")
        return redirect('inventory:inventory')
    
    if request.method == 'POST':
        # print("\n\n##################", request.POST, "\n$$$$$$$$", bool(request.FILES.get('img', False)))
        product_instance.name = request.POST['name']
        if bool(request.FILES.get('img', False)) == True:
            product_instance.pic = request.FILES['img']
        product_instance.hsn_code = request.POST['hsn']
        product_instance.min_stock_alarm = request.POST['min_stock_alarm']
        product_instance.measuring_unit_1 = request.POST['mu_1']
        if (request.POST['mu_2'] == ''): 
            product_instance.measuring_unit_2 = None
            product_instance.measuring_unit_relation = None
        else:
            product_instance.measuring_unit_2 = request.POST['mu_2']
            product_instance.measuring_unit_relation = request.POST['mr']
        product_instance.price = request.POST['price']
        product_instance.gst = request.POST['gst']
        try:
            product_instance.save()
            messages.success(request, "Edits successfull.")
            return redirect('inventory:inventory')
        except:
            messages.error(request, "Error while editing the product!")
    return render(request, 'inventory/editProduct.html', {'sb':2, 'product':product_instance})

def get_product(request, product_id):
    product = Product.objects.get(pk=product_id)
    product_dict = {}
    product_dict['name'] = product.name
    product_dict['pic_url'] = product.pic.url
    product_dict['gst'] = product.gst
    product_dict['hsn_code'] = product.hsn_code
    product_dict['mu_1'] = product.measuring_unit_1
    product_dict['price'] = product.price
    product_dict['qty'] = product.qty
    
    return HttpResponse(json.dumps(product_dict), content_type="application/json")

templates/inventory/editProduct.html
{% extends 'baseTemplate.html' %}
{% block content %}
  
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-2">
    <p class="h3 mb-0 fw-bolder">Update the Item</p>
    <div class="d-flex justify-content-end">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
          <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
        </svg>
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Alert</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure, you want to delete this item ?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
              <a href="{% url 'inventory:del-product' product.id %}" type="button" class="btn btn-danger">Yes, Delete</a>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex">
        <p class="text-dark fw-normal my-auto me-2">Status: </p>
        <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
      </div>
    </div>
  </div>

  <form enctype="multipart/form-data" action="" method="POST" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}
    <div class="row px-0 pt-4">
      <div class="col-md-3 mb-3 mb-md-0">
        <img 
            src="{{ product.pic.url }}" 
            class="mx-auto d-block" 
            alt="{{ product.name }}" 
            style="max-height:150px;max-width:100%;"
            {% comment %} width="220px" {% endcomment %}
          />
      </div>
      <div class="col-md-9 px-md-0">
        <div class="row mb-3">
          <label for="name-in" class="form-label col-sm-2 pe-0 my-auto">Name*</label>
          <div class=" col-sm-4 ps-0">
            <input type="text" class="form-control" id="name-in" name="name" value="{{ product.name }}" required>
          </div>
          <label for="hsn-in" class="form-label col-sm-3 px-0 my-auto">HSN Code*</label>
          <div class=" col-sm-3 ps-0">
            <input type="number" class="form-control" id="hsn-in" name="hsn" value="{{ product.hsn_code }}" required>
          </div>
        </div>
        <div class="row mb-3">
          <label for="mu-1-in" class="form-label col-md-4 pe-0 my-auto">Measuring Unit-1*</label>
          <div class=" col-md-2 ps-0">
            <input type="text" class="form-control" id="mu-1-in" name="mu_1" value="{{ product.measuring_unit_1 }}" required>
          </div>
          <label for="mu-2-in" class="form-label col-md-4 px-0 my-auto">Measuring Unit-2</label>
          <div class="col-md-2 ps-0">
            <input type="text" class="form-control" id="mu-2-in" value="{% if product.measuring_unit_2 != none %}{{ product.measuring_unit_2 }}{% endif   %}" name="mu_2">
          </div>
        </div>
        <div class="row mb-3">
          <label for="gst-in" class="form-label col-md-2 pe-0 my-auto">GST*</label>
          <div class="col-md-2 ps-0">
            <input type="number" class="form-control" id="gst-in" name="gst" value="{{ product.gst }}" required>
          </div>
          <div class="col-md-8">
            <div id="measuring_relation" class="d-flex justify-content-end {% if product.measuring_unit_2 == none %} invisible{% endif %}">
              <label for="mr-in" class="form-label my-auto me-2">Measuring Relation</label>
              <div class="d-flex">
                <span class="form-label my-auto mx-1">1</span>
                <span id="mu-2-put" class="form-label my-auto">{{ product.measuring_unit_2 }} </span>
                <span class="form-label my-auto mx-1"> = </span>
                <input type="number" class="form-control" style="max-width:100px;" value="{{ product.measuring_unit_relation }}" name="mr" id="mr-in">
                <span id="mu-1-put" class="form-label my-auto ms-1">{{ product.measuring_unit_1 }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <label for="actual-qty-in" class="form-label">Total Quantity in Stock*</label>
      <div class="input-group">
        <input disabled type="number" class="form-control" id="actual-qty-in" name="actual_qty" value="{{ product.qty }}" required>
        <span class="input-group-text" id="actual-qty-unit">{{ product.measuring_unit_1 }}</span>
      </div>
    </div>
    <div class="col-md-6">
      <span class="d-inline-block" tabindex="0" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Notifies you when stock goes below this value !!">
        <label for="min-stock-alarm-in" class="form-label">Minimum Stock Alarm*</label>
      </span>
      <div class="input-group">
        <input type="number" class="form-control" id="min-stock-alarm-in" name="min_stock_alarm" value="{{ product.min_stock_alarm }}" required>
        <span class="input-group-text" id="min-stock-unit">{{ product.measuring_unit_1 }}</span>
      </div>
    </div>
    <div class="col-md-6">
      <label for="img-in" class="form-label">Product Image*</label>
      <input type="file" class="form-control" id="img-in" name="img">
    </div>
    <div class="col-md-6">
      <label for="price-in" class="form-label">Price*</label>
      <div class="input-group">
        <span class="input-group-text">₹</span>
        <input type="number" class="form-control" id="price-in" name="price" value="{{ product.price }}" required>
      </div>
    </div>
    <div class="btn-group">
      <button type="submit" class="rounded mx-md-4 col-md-9 btn btn-success">Save Changes</button>
      <a href={% url 'inventory:inventory' %} class="rounded mx-md-4 col-md-3 btn btn-danger">Discard</a>
    </div>
  </form>
{% endblock %}

templates/inventory/inventory.html
{% extends 'baseTemplate.html' %}
{% block content %}
  {% comment %} {% load l10n %} {% endcomment %}
  {% load static %}
  {% load divide %}
  {% load sub %}
  {% load remainder %}
  {% load indian_num %}

  {% comment %} {% localize on %} {% endcomment %}

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 fw-bolder">Inventory</h1>
    <div class="d-flex">
      <p class="text-dark fw-normal my-auto me-2">Status: </p>
      <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <form style="min-width:30%;" action="{% url 'inventory:inventory' %}">
      <div class="justify-content-start input-group mb-sm-auto mb-3" style="max-width:100%;">
        <input type="text" class="form-control" placeholder="Search name or HSN code" aria-label="Search name or HSN code" name="search_product">
        <button class="btn btn-outline-primary" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </button>
      </div>
    </form>
    <div class="d-sm-flex" id="changeDisp">
      <a href="{% url 'inventory:add-product' %}" class="btn btn-success me-3">Add Item</a>
      <button id="btnCard" class="border border-end-0 rounded-start" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="20" fill="#505050" class="bi bi-grid-3x3" viewBox="0 0 16 16">
          <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0h13A1.5 1.5 0 0 1 16 1.5v13a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 14.5v-13zM1.5 1a.5.5 0 0 0-.5.5V5h4V1H1.5zM5 6H1v4h4V6zm1 4h4V6H6v4zm-1 1H1v3.5a.5.5 0 0 0 .5.5H5v-4zm1 0v4h4v-4H6zm5 0v4h3.5a.5.5 0 0 0 .5-.5V11h-4zm0-1h4V6h-4v4zm0-5h4V1.5a.5.5 0 0 0-.5-.5H11v4zm-1 0V1H6v4h4z"/>
        </svg>
      </button>
      <button id="btnTable" class="border rounded-end bg-transparent" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#505050" class="bi bi-list-task" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z"/>
          <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z"/>
          <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z"/>
        </svg>
      </button>
    </div>
  </div>

  <!-- Display:Tile/Card -->
  <div id="dispCard" class="row">
    {% for p in page_obj.object_list %}
    <div class="col-xl-3 col-lg-4 col-md-4 mb-3" style="max-height:400px;">
      <div class="card h-100 text-black">
        <div class="container mx-auto p-0" style="height:50%;">
          <img 
            src="{{ p.pic.url }}" 
            class="mx-auto d-block" 
            alt="{{ p.name }}" 
            style="max-height:100%;max-width:100%;"
          />
          <div class="overlay">
            <a href="{% url 'inventory:edit-product' p.id %}" class="icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
              </svg>
            </a>
          </div>
        </div>
        <div class="card-body">
          <div class="text-center mt-1">
            <h4 class="card-title">
              {{ p.name }}         <!--   -{{ p.id }}   -->
            </h4>
            <h5 class="text-primary mb-1 pb-3">
              {{ p.price|indian_num }}
            </h5>
          </div>
          <div class="text-center">
            <div class="p-3 mx-n3 mb-2" style="background-color: #eff1f2;">
              <h5 class="mb-0">
                {{ p.qty }} 
                {{ p.measuring_unit_1 }}
              </h5>
              {% comment %} {% if p.measuring_unit_2 != none %}
                <hr class="m-1">
                <h5 class="mb-0"> 
                  {{ p.qty|divide:p.measuring_unit_relation }} 
                  {{ p.measuring_unit_2 }}
                  {% if p.qty|remainder:p.measuring_unit_relation %}
                    {{ p.qty|remainder:p.measuring_unit_relation }}
                    {{ p.measuring_unit_1 }}
                  {% endif %}
                </h5>
              {% endif %} {% endcomment %}
            </div>
          </div>
        </div>
      </div>
    </div> 
    {% endfor %}
  </div>

  <!-- Display:Table/List -->
  <table id="dispTable" class="table d-none">
    <thead class="sticky-top">
      <tr>
        <th scope="col">Img</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">HSN</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      {% for p in page_obj.object_list %}
      <tr>
        <th scope="row"><img src="{{ p.pic.url }}" style="max-width:90px;max-height:90px" alt="{{ p.name }}"/></th>
        <td>{{ p.name }}</td>
        <td>₹{{ p.price }}</td>
        <td>
          <h7 class='fw-bold'>{{ p.qty }}</h7>
          {{ p.measuring_unit_1 }}
          {% comment %} {% if p.measuring_unit_2 != none %}
          <br>
            <h7 class="fw-bold mb-0"> 
              {{ p.qty|divide:p.measuring_unit_relation }} 
            </h7>
            {{ p.measuring_unit_2 }}
            {% if p.qty|remainder:p.measuring_unit_relation %}
            <h7 class="fw-bold mb-0"> 
              {{ p.qty|remainder:p.measuring_unit_relation }}
            </h7>
            {{ p.measuring_unit_1 }}
            {% endif %}
            </h7>
          {% endif %} {% endcomment %}
        </td>
        <td>{{ p.hsn_code }}</td>
        <td>
          <a href="{% url 'inventory:edit-product' p.id %}" class="btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg justify-content-center">
      {%if page_obj.has_previous %}
      <li class="page-item ">
        <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      {% endif %}
      <li class="page-item"><a class="page-link active" href="#">{{page_obj.number}}</a></li>
      {%if page_obj.has_next %}
      <li class="page-item ">
        <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  
  {% comment %} {% endlocalize %} {% endcomment %}


{% endblock %}