customer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "customer"
urlpatterns = [
    path('', views.customer, name="customer"),
    # path('view-customer/', views.view_customer, name="view-customer"),
    path('add-customer/', views.add_customer, name="add-customer"),
    path('edit-customer/<customer_id>/', views.edit_customer, name="edit-customer"),
    path('del-customer/<customer_id>/', views.del_customer, name="del-customer"),
    path('get-customer/<customer_id>/', views.get_customer, name='get-customer'),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

ims/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase/', include('purchase.urls')),
    path('seller/', include('seller.urls')),
    path('customer/', include('customer.urls')),
    path('sale/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('add-product/', views.add_product, name="add-product"),
    path('edit-product/<product_id>/', views.edit_product, name="edit-product"),
    path('del-product/<product_id>/', views.delete_product, name="del-product"),
    path('get-product/<product_id>/', views.get_product, name='get-product'),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

customer/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    gstin = models.CharField(max_length=15)
    address1 = models.TextField()
    address2 = models.TextField()
    mob_no = models.IntegerField(blank=True, null=True, unique=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    pic = models.ImageField(default='defaultUser.png', upload_to='customer_pics')
    
    def __str__(self):
        return self.name

customer/views.py
import json
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .models import Customer
from django.core.paginator import Paginator
from django.db.models import Q, ProtectedError
from django.db.models.functions import Lower
from django.contrib import messages


# Create your views here.
def customer(request):
    # For searching the Customers
    search_customer = request.GET.get('search_customer')
    if search_customer:
        customer = Customer.objects.exclude(id=1).filter(Q(name__icontains=search_customer))
    else:
        # If not searched, return default posts
        customer = Customer.objects.all().exclude(id=1).order_by(Lower("name"))
    
    p = Paginator(customer, 12)  # creating a paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    
    return render(request, 'customer/customer.html', {'sb':4, 'page_obj':page_obj})

def add_customer(request):
    if request.method == "POST":
        instance = Customer()
        instance.name = request.POST['name']
        instance.gstin = request.POST['gstin']
        instance.address1 = request.POST['address1']
        instance.address2 = request.POST['address2']
        if (request.POST['mob_no'] != ''):
            instance.mob_no = request.POST['mob_no']
        if (request.POST['email'] != ''): 
            instance.email = request.POST['email']
        if bool(request.FILES.get('pic', False)) == True:
            instance.pic = request.FILES['pic']
        try:
            instance.save()
            messages.success(request, "Customer added successfully.")
            return redirect('customer:customer')
        except:
            messages.error(request, "Error, customer not added!")
    return render(request, 'customer/addCustomer.html', {'sb':4})

def edit_customer(request, customer_id):
    if customer_id == 1:
        raise Http404
    try:
        customer_instance = Customer.objects.get(pk=customer_id)
    except:
        messages.error(request, "Customer not found!")
        return redirect('customer:customer')
    
    if request.method == 'POST':
        if (request.POST['name'] != ''):
            customer_instance.name = request.POST['name']
        if (request.POST['gstin'] != ''):
            customer_instance.gstin = request.POST['gstin']
        if (request.POST['mob_no'] != ''):
            customer_instance.mob_no = request.POST['mob_no']
        if (request.POST['address1'] != ''):
            customer_instance.address1 = request.POST['address1']
        if (request.POST['address2'] != ''):
            customer_instance.address2 = request.POST['address2']
        if (request.POST['email'] != ''):
            customer_instance.email = request.POST['email']
        if bool(request.FILES.get('pic', False)) == True:
            customer_instance.pic = request.FILES['pic']
        try:
            customer_instance.save()
            messages.success(request, "Edits successfull.")
            return redirect('customer:customer')
        except:
            messages.error(request, "Error while editing the customer!")
    return render(request, 'customer/editCustomer.html', {'sb':4, 'customer':customer_instance})

def del_customer(request, customer_id):
    if customer_id == 1:
        messages.error(request, "Access Restricted!!")
        return redirect('customer:customer')
    
    try:
        customer_instance = Customer.objects.get(pk=customer_id)
    except:
        messages.error(request, "Customer not found!")
        return redirect('customer:customer')
    
    try:
        customer_instance.delete()
        messages.success(request, "Customer successfully removed.")
    except ProtectedError:
        messages.error(request, "Customer can't be deleted!!")
    except:
        messages.error(request, "Error while removing the customer!")
    finally:
        return redirect('customer:customer')

def get_customer(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    customer_dict = {}
    customer_dict['name'] = customer.name
    customer_dict['pic_url'] = customer.pic.url
    customer_dict['gstin'] = customer.gstin
    customer_dict['mob_no'] = customer.mob_no
    customer_dict['email'] = customer.email
    customer_dict['address1'] = customer.address1
    customer_dict['address2'] = customer.address2
    
    return HttpResponse(json.dumps(customer_dict), content_type="application/json")

templates/customer/addCustomer.html
{% extends 'baseTemplate.html' %}
{% block content %}
  
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-2">
    <p class="h3 mb-0 fw-bolder">Add Customer</p>
    <div class="d-flex">
      <p class="text-dark fw-normal my-auto me-2">Status: </p>
      <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
    </div>
  </div>

  <form enctype="multipart/form-data" action="" method="POST" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}
    <div class="col-md-4">
      <label for="name-in" class="form-label">Company Name*</label>
      <input type="text" class="form-control" id="name-in" placeholder="Company's registered name" name="name" required>
    </div>
    <div class="col-md-4">
      <label for="gstin-in" class="form-label">GSTIN*</label>
      <input type="text" class="form-control" id="gstin-in" name="gstin" required>
    </div>
    <div class="col-md-4">
      <label for="mob-in" class="form-label">Mobile Number</label>
      <input type="number" class="form-control" id="mob-in" name="mob_no">
    </div>
    <div class="col-md-6">
      <label for="add1-in" class="form-label">Address Line-1*</label>
      <input type="text" class="form-control" id="add1-in" placeholder="Company No. , Area , Locality" name="address1" required>
    </div>
    <div class="col-md-6">
      <label for="add2-in" class="form-label">Address Line-2*</label>
      <input type="text" class="form-control" id="add2-in" placeholder="City , State , Pin Code , Country" name="address2" required>
    </div>
    <div class="col-md-6">
      <label for="email-in" class="form-label">Email</label>
      <input type="email" class="form-control" id="email-in" name="email">
    </div>
    <div class="col-md-6 mb-3">
      <label for="img-in" class="form-label">Image</label>
      <input type="file" class="form-control" id="img-in" name="pic">
    </div>
    <div class="btn-group">
      <button type="submit" class="rounded mx-md-4 col-md-9 btn btn-success">Submit</button>
      <a href={% url 'customer:customer' %} class="rounded mx-md-4 col-md-3 btn btn-danger">Discard</a>
    </div>
  </form>
{% endblock %}

templates/customer/customer.html
{% extends 'baseTemplate.html' %}
{% block content %}
  {% load static %}
  {% load divide %}
  {% load sub %}
  {% load remainder %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 fw-bolder">Customer</h1>
    <div class="d-flex">
      <p class="text-dark fw-normal my-auto me-2">Status: </p>
      <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <form style="min-width:30%;" action="{% url 'customer:customer' %}">
      <div class="justify-content-start input-group mb-sm-auto mb-3" style="max-width:100%;">
        <input type="text" class="form-control" placeholder="Search name" aria-label="Search name" name="search_customer">
        <button class="btn btn-outline-primary" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </button>
      </div>
    </form>
    <div class="d-sm-flex" id="changeDisp">
      <a href="{% url 'customer:add-customer' %}" class="btn btn-success">Add Customer</a>
      {% comment %} <a href="{% url 'inventory:add-product' %}" class="btn btn-success">Create customer</a> {% endcomment %}
    </div>
  </div>

  <!-- Display:Table/List -->
  <table class="table">
    <thead class="sticky-top">
      <tr>
        <th scope="col">Img</th>
        <th scope="col">Name</th>
        <th scope="col">GSTIN</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">Address</th>
        <th scope="col">Email</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      {% for p in page_obj.object_list %}
      <tr>
        <th scope="row"><img src="{{ p.pic.url }}" style="max-width:90px;max-height:90px" alt="{{ p.name }}"/></th>
        <td>{{ p.name }}</td>
        <td>{% if p.gstin %}{{ p.gstin }}{% else %}-{% endif %}</td>
        <td>{% if p.mob_no %}{{ p.mob_no }}{% else %}-{% endif %}</td>
        <td>
          {% if p.address1 %}{{ p.address1 }}{% else %}-{% endif %}
          <br>
          {% if p.address2 %}{{ p.address2 }}{% else %}-{% endif %}
        </td>
        <td>{% if p.email %}{{ p.email }}{% else %}-{% endif %}</td>
        <td>
          <a href="{% url 'customer:edit-customer' p.id %}" class="btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if page_obj %}
  <nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg justify-content-center">
      {%if page_obj.has_previous %}
      <li class="page-item ">
        <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      {% endif %}
      <li class="page-item"><a class="page-link active" href="#">{{page_obj.number}}</a></li>
      {%if page_obj.has_next %}
      <li class="page-item ">
        <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
    {% endif %}
  
  
{% endblock %}

templates/customer/editCustomer.html
{% extends 'baseTemplate.html' %}
{% block content %}
  
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-2">
    <p class="h3 mb-0 fw-bolder">Update the Item</p>
    <div class="d-flex justify-content-end">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
          <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
        </svg>
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Alert</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure, you want to delete this customer ?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
              <a href="{% url 'customer:del-customer' customer.id %}" type="button" class="btn btn-danger">Yes, Delete</a>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex">
        <p class="text-dark fw-normal my-auto me-2">Status: </p>
        <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
      </div>
    </div>
  </div>

  <form enctype="multipart/form-data" action="" method="POST" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}
    <div class="row px-0 pt-4">
      <div class="col-md-3 mb-3 mb-md-0">
        <img 
            src="{{ customer.pic.url }}" 
            class="mx-auto d-block" 
            alt="{{ customer.name }}" 
            style="max-height:150px;max-width:100%;"
            {% comment %} width="220px" {% endcomment %}
        />
      </div>
      <div class="col-md-9 px-md-0">
        <div class="row">
          <label for="name-in" class="form-label col-md-3 my-auto">Company Name*</label>
          <div class=" col-md-4 ps-0 mb-3">
            <input type="text" class="form-control" id="name-in" name="name" value="{{ customer.name }}" required>
          </div>
          <label for="gstin-in" class="form-label col-md-2 my-auto">GSTIN*</label>
          <div class=" col-md-3 ps-0 mb-3">
            <input type="text" class="form-control" id="gstin-in" name="gstin" value="{% if customer.gstin %}{{ customer.gstin }}{% endif %}">
          </div>
        </div>
        <div class="row">
          <label for="mob-in" class="form-label col-md-3 my-auto">Mobile Number</label>
          <div class=" col-md-3 ps-0 mb-3">
            <input type="number" class="form-control" id="mob-in" name="mob_no" value="{% if customer.mob_no %}{{ customer.mob_no }}{% endif %}">
          </div>
          <label for="email-in" class="form-label col-md-2 my-auto">Email</label>
          <div class="col-md-4 ps-0 mb-3">
            <input type="email" class="form-control" id="email-in" name="email" value="{% if customer.email %}{{ customer.email }}{% endif %}">
          </div>
        </div>
        <div class="row">
          <label for="img-in" class="form-label col-md-2 my-auto">Image</label>
          <div class="col-md-10 ps-0 mb-3">
            <input type="file" class="form-control" id="img-in" name="pic">
          </div>
        </div>
      </div>
    </div>
    <div class="row px-0 mt-md-3">
      <label for="add-in-1" class="col-md-2 my-auto form-label">Address Line-1*</label>
      <div class="col-md-4 px-md-0">
        <input type="text" class="form-control" id="add-in" name="address1" value="{% if customer.address1 %}{{ customer.address1 }}{% endif %}" required>
      </div>
      <label for="add-in-2" class="col-md-2 my-auto form-label">Address Line-2*</label>
      <div class="col-md-4 px-md-0">
        <input type="text" class="form-control" id="add-in" name="address2" value="{% if customer.address2 %}{{ customer.address2 }}{% endif %}" required>
      </div>
    </div>
    <div class="btn-group mt-4">
      <button type="submit" class="rounded mx-md-4 col-md-9 btn btn-success">Save Changes</button>
      <a href={% url 'customer:customer' %} class="rounded mx-md-4 col-md-3 btn btn-danger">Discard</a>
    </div>
  </form>
{% endblock %}