ims/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase/', include('purchase.urls')),
    path('seller/', include('seller.urls')),
    path('customer/', include('customer.urls')),
    path('sale/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "inventory"
urlpatterns = [
    path('', views.inventory, name="inventory"),
    path('add-product/', views.add_product, name="add-product"),
    path('edit-product/<product_id>/', views.edit_product, name="edit-product"),
    path('del-product/<product_id>/', views.delete_product, name="del-product"),
    path('get-product/<product_id>/', views.get_product, name='get-product'),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

seller/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "seller"
urlpatterns = [
    path('', views.seller, name="seller"),
    # path('view-seller/', views.view_seller, name="view-seller"),
    path('add-seller/', views.add_seller, name="add-seller"),
    path('edit-seller/<seller_id>/', views.edit_seller, name="edit-seller"),
    path('del-seller/<seller_id>/', views.del_seller, name="del-seller"),
    path('get-seller/<seller_id>/', views.get_seller, name='get-seller'),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

seller/models.py
from django.db import models

# Create your models here.
class Seller(models.Model):
    name = models.CharField(max_length=50)
    gstin = models.CharField(max_length=15, blank=True, null=True)
    mob_no = models.IntegerField(blank=True, null=True, unique=True)
    address = models.TextField(blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    pic = models.ImageField(default='defaultUser.png', upload_to='seller_pics')
    
    def __str__(self):
        return self.name

seller/views.py
import json
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect, HttpResponse
from .models import Seller
from django.core.paginator import Paginator
from django.db.models import Q, ProtectedError
from django.db.models.functions import Lower
from django.contrib import messages


# Create your views here.
def seller(request):
    # For searching the Sellers
    search_seller = request.GET.get('search_seller')
    if search_seller:
        seller = Seller.objects.exclude(id=1).filter(Q(name__icontains=search_seller))
    else:
        # If not searched, return default posts
        seller = Seller.objects.all().exclude(id=1).order_by(Lower("name"))
    
    p = Paginator(seller, 12)  # creating a paginator object
    # getting the desired page number from url
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = p.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = p.page(p.num_pages)
    
    return render(request, 'seller/seller.html', {'sb':6, 'page_obj':page_obj})

def add_seller(request):
    if request.method == "POST":
        instance = Seller()
        instance.name = request.POST['name']
        if (request.POST['gstin'] != ''):
            instance.gstin = request.POST['gstin']
        if (request.POST['mob_no'] != ''):
            instance.mob_no = request.POST['mob_no']
        if (request.POST['address'] != ''):
            instance.address = request.POST['address']
        if (request.POST['email'] != ''): 
            instance.email = request.POST['email']
        if bool(request.FILES.get('pic', False)) == True:
            instance.pic = request.FILES['pic']
        try:
            instance.save()
            messages.success(request, "Seller added successfully.")
            return redirect('seller:seller')
        except:
            messages.error(request, "Error, seller not added!")
    return render(request, 'seller/addSeller.html', {'sb':6})

def edit_seller(request, seller_id):
    if seller_id == 1:
      raise Http404
    try:
        seller_instance = Seller.objects.get(pk=seller_id)
    except:
        messages.error(request, "Seller not found!")
        return redirect('seller:seller')
    
    if request.method == 'POST':
        seller_instance.name = request.POST['name']
        seller_instance.gstin = request.POST['gstin']
        if (request.POST['mob_no'] == ''):
            seller_instance.mob_no = None
        else:
            seller_instance.mob_no = request.POST['mob_no']
        seller_instance.address = request.POST['address']
        seller_instance.email = request.POST['email']
        if bool(request.FILES.get('pic', False)) == True:
            seller_instance.pic = request.FILES['pic']
        try:
            seller_instance.save()
            messages.success(request, "Edits successfull.")
            return redirect('seller:seller')
        except:
            messages.error(request, "Error while editing the seller!")
    return render(request, 'seller/editSeller.html', {'sb':6, 'seller':seller_instance})

def del_seller(request, seller_id):
    if seller_id == 1:
        messages.error(request, "Access Restricted!!")
        return redirect('seller:seller')
    
    try:
        seller_instance = get_object_or_404(Seller, pk=seller_id)
    except:
        messages.error(request, "Seller not found!")
        return redirect('seller:seller')

    try:
        seller_instance.delete()
        messages.success(request, "Seller successfully removed.")
    except ProtectedError:
        messages.error(request, "Seller can't be deleted!!")
    except:
        messages.error(request, "Error while removing the seller!")
    finally:
        return redirect('seller:seller')


def get_seller(request, seller_id):
    seller = Seller.objects.get(pk=seller_id)
    seller_dict = {}
    seller_dict['name'] = seller.name
    seller_dict['pic_url'] = seller.pic.url
    seller_dict['gstin'] = seller.gstin
    seller_dict['mob_no'] = seller.mob_no
    seller_dict['email'] = seller.email
    seller_dict['address'] = seller.address
    
    return HttpResponse(json.dumps(seller_dict), content_type="application/json")

templates/seller/addSeller.html
{% extends 'baseTemplate.html' %}
{% block content %}
  
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-2">
    <p class="h3 mb-0 fw-bolder">Add Seller</p>
    <div class="d-flex">
      <p class="text-dark fw-normal my-auto me-2">Status: </p>
      <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
    </div>
  </div>

  <form enctype="multipart/form-data" action="" method="POST" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}
    <div class="col-md-4">
      <label for="name-in" class="form-label">Name*</label>
      <input type="text" class="form-control" id="name-in" name="name" autocomplete="on" required>
    </div>
    <div class="col-md-4">
      <label for="gstin-in" class="form-label">GSTIN</label>
      <input type="text" class="form-control" id="gstin-in" name="gstin">
    </div>
    <div class="col-md-4">
      <label for="mob-in" class="form-label">Mobile Number</label>
      <input type="number" class="form-control" id="mob-in" name="mob_no">
    </div>
    <div class="col-md-6">
      <label for="add-in" class="form-label">Address</label>
      <input type="text" class="form-control" id="add-in" name="address">
    </div>
    <div class="col-md-6">
      <label for="email-in" class="form-label">Email</label>
      <input type="email" class="form-control" id="email-in" name="email">
    </div>
    <div class="col-md-12 mb-3">
      <label for="img-in" class="form-label">Image</label>
      <input type="file" class="form-control" id="img-in" name="pic">
    </div>
    <div class="btn-group">
      <button type="submit" class="rounded mx-md-4 col-md-9 btn btn-success">Submit</button>
      <a href={% url 'seller:seller' %} class="rounded mx-md-4 col-md-3 btn btn-danger">Discard</a>
    </div>
  </form>
{% endblock %}

templates/seller/editSeller.html
{% extends 'baseTemplate.html' %}
{% block content %}
  
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-2">
    <p class="h3 mb-0 fw-bolder">Update the Item</p>
    <div class="d-flex justify-content-end">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
          <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
        </svg>
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Alert</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure, you want to delete this seller ?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" data-bs-dismiss="modal">No</button>
              <a href="{% url 'seller:del-seller' seller.id %}" type="button" class="btn btn-danger">Yes, Delete</a>
            </div>
          </div>
        </div>
      </div>
      <div class="d-flex">
        <p class="text-dark fw-normal my-auto me-2">Status: </p>
        <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
      </div>
    </div>
  </div>

  <form enctype="multipart/form-data" action="" method="POST" class="row g-3 needs-validation" novalidate>
    {% csrf_token %}
    <div class="row px-0 pt-4">
      <div class="col-md-3 mb-3 mb-md-0">
        <img 
            src="{{ seller.pic.url }}" 
            class="mx-auto d-block" 
            alt="{{ seller.name }}" 
            style="max-height:150px;max-width:100%;"
            {% comment %} width="220px" {% endcomment %}
        />
      </div>
      <div class="col-md-9 px-md-0">
        <div class="row">
          <label for="name-in" class="form-label col-md-2 my-auto">Name*</label>
          <div class=" col-md-4 ps-0 mb-3">
            <input type="text" class="form-control" id="name-in" name="name" value="{{ seller.name }}" required>
          </div>
          <label for="gstin-in" class="form-label col-md-2 my-auto">GSTIN</label>
          <div class=" col-md-4 ps-0 mb-3">
            <input type="text" class="form-control" id="gstin-in" name="gstin" value="{% if seller.gstin %}{{ seller.gstin }}{% endif %}">
          </div>
        </div>
        <div class="row">
          <label for="mob-in" class="form-label col-md-3 my-auto">Mobile Number</label>
          <div class=" col-md-3 ps-0 mb-3">
            <input type="number" class="form-control" id="mob-in" name="mob_no" value="{% if seller.mob_no %}{{ seller.mob_no }}{% endif %}">
          </div>
          <label for="email-in" class="form-label col-md-2 my-auto">Email</label>
          <div class="col-md-4 ps-0 mb-3">
            <input type="email" class="form-control" id="email-in" name="email" value="{% if seller.email %}{{ seller.email }}{% endif %}">
          </div>
        </div>
        <div class="row">
          <label for="img-in" class="form-label col-md-2 my-auto">Image</label>
          <div class="col-md-10 ps-0 mb-3">
            <input type="file" class="form-control" id="img-in" name="pic">
          </div>
        </div>
      </div>
    </div>
    <div class="row px-0 mt-md-3">
      {% comment %} <div class="col-md-12"> {% endcomment %}
          <label for="add-in" class="col-md-2 my-auto form-label">Address</label>
          <div class="col-md-10 px-md-0">
            <input type="text" class="form-control" id="add-in" name="address" value="{% if seller.address %}{{ seller.address }}{% endif %}">
          </div>
      {% comment %} </div> {% endcomment %}
    </div>
    <div class="btn-group mt-4">
      <button type="submit" class="rounded mx-md-4 col-md-9 btn btn-success">Save Changes</button>
      <a href={% url 'seller:seller' %} class="rounded mx-md-4 col-md-3 btn btn-danger">Discard</a>
    </div>
  </form>
{% endblock %}

templates/seller/seller.html
{% extends 'baseTemplate.html' %}
{% block content %}
  {% load static %}
  {% load divide %}
  {% load sub %}
  {% load remainder %}
  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 fw-bolder">Seller</h1>
    <div class="d-flex">
      <p class="text-dark fw-normal my-auto me-2">Status: </p>
      <p class="border border-1 rounded text-dark fw-bold my-auto text-capitalize p-1" style="color: #6a6a6a!important;">{{ user.profile.status }}</p>
    </div>
  </div>

  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <form style="min-width:30%;" action="{% url 'seller:seller' %}">
      <div class="justify-content-start input-group mb-sm-auto mb-3" style="max-width:100%;">
        <input type="text" class="form-control" placeholder="Search name" aria-label="Search name" name="search_seller">
        <button class="btn btn-outline-primary" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        </button>
      </div>
    </form>
    <div class="d-sm-flex" id="changeDisp">
      <a href="{% url 'seller:add-seller' %}" class="btn btn-success">Add Seller</a>
      {% comment %} <a href="{% url 'inventory:add-product' %}" class="btn btn-success">Create seller</a> {% endcomment %}
    </div>
  </div>

  <!-- Display:Table/List -->
  <table class="table">
    <thead class="sticky-top">
      <tr>
        <th scope="col">Img</th>
        <th scope="col">Name</th>
        <th scope="col">GSTIN</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">Address</th>
        <th scope="col">Email</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>
      {% for p in page_obj.object_list %}
      <tr>
        <th scope="row"><img src="{{ p.pic.url }}" style="max-width:90px;max-height:90px" alt="{{ p.name }}"/></th>
        <td>{{ p.name }}</td>
        <td>{% if p.gstin %}{{ p.gstin }}{% else %}-{% endif %}</td>
        <td>{% if p.mob_no %}{{ p.mob_no }}{% else %}-{% endif %}</td>
        <td>{% if p.address %}{{ p.address }}{% else %}-{% endif %}</td>
        <td>{% if p.email %}{{ p.email }}{% else %}-{% endif %}</td>
        <td>
          <a href="{% url 'seller:edit-seller' p.id %}" class="btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if page_obj %}
  <nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg justify-content-center">
      {%if page_obj.has_previous %}
      <li class="page-item ">
        <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Previous</a>
      </li>
      {% endif %}
      <li class="page-item"><a class="page-link active" href="#">{{page_obj.number}}</a></li>
      {%if page_obj.has_next %}
      <li class="page-item ">
        <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link">Next</a>
      </li>
      {% endif %}
    </ul>
  </nav>
    {% endif %}
  
  
{% endblock %}