customer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "customer"
urlpatterns = [
    path('', views.customer, name="customer"),
    # path('view-customer/', views.view_customer, name="view-customer"),
    path('add-customer/', views.add_customer, name="add-customer"),
    path('edit-customer/<customer_id>/', views.edit_customer, name="edit-customer"),
    path('del-customer/<customer_id>/', views.del_customer, name="del-customer"),
    path('get-customer/<customer_id>/', views.get_customer, name='get-customer'),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

ims/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('accounts.urls')),
    path('inventory/', include('inventory.urls')),
    path('purchase/', include('purchase.urls')),
    path('seller/', include('seller.urls')),
    path('customer/', include('customer.urls')),
    path('sale/', include('sale.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchase/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "purchase"
urlpatterns = [
    path('', views.purchase, name="purchase"),
    path('create-purchase/', views.create_purchase, name="create-purchase"),
    path('view-purchase/<purchase_order_id>/', views.view_purchase, name="view-purchase"),
    # path('edit-purchase/<purchase_order_id>/', views.edit_purchase, name="edit-purchase"),
    # path('del-purchase/<purchase_order_id>/', views.del_purchase, name="del-purchase"),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

sale/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "sale"
urlpatterns = [
    path('', views.sale, name="sale"),
    path('create-sale/', views.create_sale, name="create-sale"),
    path('view-sale/<sale_order_id>/', views.view_sale, name="view-sale"),
    # path('edit-sale/<sale_order_id>/', views.edit_sale, name="edit-sale"),
    # path('del-sale/<sale_order_id>/', views.del_sale, name="del-sale"),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

seller/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views

app_name = "seller"
urlpatterns = [
    path('', views.seller, name="seller"),
    # path('view-seller/', views.view_seller, name="view-seller"),
    path('add-seller/', views.add_seller, name="add-seller"),
    path('edit-seller/<seller_id>/', views.edit_seller, name="edit-seller"),
    path('del-seller/<seller_id>/', views.del_seller, name="del-seller"),
    path('get-seller/<seller_id>/', views.get_seller, name='get-seller'),
    # path('logout', views.logout, name="logout"),
    # path('activate/<uidb64>/<token>', views.activate, name="activate")
]

templates/baseTemplate.html
{% load static %}
<!DOCTYPE html>
<html>

  <head ad>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>IMS</title>

    <!-- Bootstrap CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/baseTemplate.css' %}">
    <!-- Scrollbar Custom CSS -->
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css"> {% endcomment %}

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    
    <!-- Select2 - Select Input with Search Functionality -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <!-- Convert to PDF -->
    {% comment %} <script src="https://unpkg.com/jspdf@latest/dist/jspdf.umd.min.js"></script> {% endcomment %}
    <script src="{% static 'js/printThis.js' %}"></script>
    {% comment %} <script src="{% static 'printCustom.js' %}"></script> {% endcomment %}
  
  </head>

<body>

  <div class="wrapper">
    
    <!-- Sidebar  -->
    <nav id="sidebar">
      <div class="sidebar-header">
        {% comment %} <a href="/" class="nav-link {% if sb == 1 %}active{% endif %}" aria-current="page"> {% endcomment %}
          <img class="mb-2" src="{% static 'img/logo.png' %}" height="40px" width="40px" />
          <span class="fw-medium mb-4">Company</span>
        {% comment %} </a> {% endcomment %}
      </div>
      <ul class="nav nav-pills flex-column mb-auto mt-4">
        <li class="p-1">
          <a href="/" class="nav-link {% if sb == 1 %}active{% endif %}" aria-current="page">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
              <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg>
            <span class="ms-1">Home</span>
          </a>
        </li>
        <li class="p-1">
          <a href="/inventory" class="nav-link {% if sb == 2 %}active{% endif %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
              <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2l-2.218-.887zm3.564 1.426L5.596 5 8 5.961 14.154 3.5l-2.404-.961zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923l6.5 2.6zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464L7.443.184z"/>
            </svg>
            <span class="ms-1">Inventory</span>
          </a>
        </li>
        <li class="p-1">
          <a href="{% url 'sale:sale' %}" class="nav-link {% if sb == 3 %}active{% endif %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-receipt-cutoff" viewBox="0 0 16 16">
              <path d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zM11.5 4a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1zm0 2a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1z"/>
              <path d="M2.354.646a.5.5 0 0 0-.801.13l-.5 1A.5.5 0 0 0 1 2v13H.5a.5.5 0 0 0 0 1h15a.5.5 0 0 0 0-1H15V2a.5.5 0 0 0-.053-.224l-.5-1a.5.5 0 0 0-.8-.13L13 1.293l-.646-.647a.5.5 0 0 0-.708 0L11 1.293l-.646-.647a.5.5 0 0 0-.708 0L9 1.293 8.354.646a.5.5 0 0 0-.708 0L7 1.293 6.354.646a.5.5 0 0 0-.708 0L5 1.293 4.354.646a.5.5 0 0 0-.708 0L3 1.293 2.354.646zm-.217 1.198.51.51a.5.5 0 0 0 .707 0L4 1.707l.646.647a.5.5 0 0 0 .708 0L6 1.707l.646.647a.5.5 0 0 0 .708 0L8 1.707l.646.647a.5.5 0 0 0 .708 0L10 1.707l.646.647a.5.5 0 0 0 .708 0L12 1.707l.646.647a.5.5 0 0 0 .708 0l.509-.51.137.274V15H2V2.118l.137-.274z"/>
            </svg>
            <span class="ms-1">Sale</span>
          </a>
        </li>
        <li class="p-1">
          <a href="{% url 'customer:customer' %}" class="nav-link {% if sb == 4 %}active{% endif %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-up" viewBox="0 0 16 16">
              <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.354-5.854 1.5 1.5a.5.5 0 0 1-.708.708L13 11.707V14.5a.5.5 0 0 1-1 0v-2.793l-.646.647a.5.5 0 0 1-.708-.708l1.5-1.5a.5.5 0 0 1 .708 0ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
              <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
            </svg>
            <span class="ms-1">Customers</span>
          </a>
        </li>
        <li class="p-1">
          <a href="{% url 'purchase:purchase' %}" class="nav-link {% if sb == 5 %}active{% endif %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
              <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
            </svg>
            <span class="ms-1">Purchase</span>
          </a>
        </li>
        <li class="p-1">
          <a href="{% url 'seller:seller' %}" class="nav-link {% if sb == 6 %}active{% endif %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-down" viewBox="0 0 16 16">
              <path d="M12.5 9a3.5 3.5 0 1 1 0 7 3.5 3.5 0 0 1 0-7Zm.354 5.854 1.5-1.5a.5.5 0 0 0-.708-.708l-.646.647V10.5a.5.5 0 0 0-1 0v2.793l-.646-.647a.5.5 0 0 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0ZM11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
              <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
            </svg>
            <span class="ms-1">Sellers</span>
          </a>
        </li>
      </ul>
    </nav>
    <!-- Sidebar Ends -->

    <!-- Side-Page Content  -->
    <div id="content" class="p-0" style="overflow-x:auto;">
          
      <!-- Top Navigation Bar -->
      <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          
          <!-- Sidebar Toggler -->
          <button type="button" id="sidebarCollapse" class="btn btn-dark">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="#ffffff" class="bi bi-list" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
            </svg>
            <span>Toggle Sidebar</span>
          </button>
          <!-- Sidebar Toggler Ends -->
          
          <!-- Profile -->
          {% if not user.is_authenticated %}
          <a class="btn btn-secondary" href="/signin" role="button">Login</a>
          {% else %}
          <div class="d-flex">
            <p class="text-capitalize fw-normal text-dark my-auto pt-1 me-2">{{ user.username }}</p>
            <div class="dropdown me-4">
              <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img
                    src="{{ user.profile.profile_pic.url }}"
                    class="rounded-circle"
                    height="35px"
                    alt="Black and White Portrait of a Man"
                    loading="lazy"
                />
              </a>
              <ul class="dropdown-menu" style="left: -122px;">
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="/signout">Logout</a></li>
              </ul>
            </div>
          </div>
          {% endif %}
          <!-- Proflie Ends -->

        </div>
      </nav>
      <!-- Top Navigation Bar Ends -->

      <!-- Page Content Starts -->
      <div class="main-class px-3 py-4">
        <div class="container-fluid">
          
          {% if not user.is_authenticated %}
          
            <div class="text-center my-3">
              {% comment %} <i class="bi bi-exclamation-octagon-fill"></i> {% endcomment %}
              <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="#3c3c3c" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
              </svg>
              {% comment %} <img class="d-block mx-auto mb-4" src="{% static 'img/default.png' %}" alt="" width="72" height="65"> {% endcomment %}
              <h1 class="display-5 text-body-emphasis" style="font-weight: 500;">Please, Login to continue !!</h1>
              <div class="col-lg-6 mx-auto my-3">
                {% comment %} <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p> {% endcomment %}
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                  <a class="btn btn-primary btn-lg" href="/signin" role="button">Login</a>
                  {% comment %} <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button> {% endcomment %}
                </div>
              </div>
            </div>
          {% else %}
          
            {% block content %}
            {% endblock %}
          
          {% endif %}
          
          {% if messages %}
            {% for message in messages %}
              <div class="toast-container position-fixed bottom-0 end-0 p-3">
                <div class="toast align-items-center text-white text-bg-{{ message.tags }}" role="alert" aria-live="assertive" aria-atomic="true">
                  <div class="d-flex">
                    <div class="toast-body fs-6 fw-medium">
                      {{ message|safe }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% endif %}

        </div>
      </div>
      <!-- Side-Page Content Ends -->
      
    </div>
    <!-- Page Content Ends -->
  
  </div>
  <!-- Wrapper Ends -->

  <script src="{% static 'js/baseTemplate.js' %}"></script>
   
</body>

</html>